# Task 2: Read and prepare the data for Risk of Recidivism	
# Q1: Import modules needed to implement predictive maintenance, R is used (ggplot and dplyr)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)

# Task 2: Read and prepare the data for Risk of Recidivism
# Q2: Read the non violent dataset to read the number of rows
# Note: We are given a dataset that has both violent and non violent datasets combined into one
raw_data <- read.csv("C:/Users/benny/Desktop/My-Docs/Jobs-2022/Course-NotJob/Module4-Downloads/Project/compas-scores-two-years.csv")

# Number of rows
nrow(raw_data)

# Task 2: Read and prepare the data for Risk of Recidivism
# Q3: Remove rows based on following conditions
df <- dplyr::select( raw_data, age, c_charge_degree, race, age_cat, score_text, sex, priors_count, days_b_screening_arrest, decile_score, is_recid, two_year_recid, c_jail_in, c_jail_out) %>%
  filter(days_b_screening_arrest <= 30) %>%
  filter(days_b_screening_arrest >= -30) %>%
  filter(is_recid != -1) %>%
  filter(c_charge_degree != "0") %>%
  filter(score_text != 'N/A')

# Task 2: Read and prepare the data for Risk of Recidivism
# Q4: Get new column longer length of stay
df$length_of_stay <- as.numeric( as.Date(df$c_jail_out, format = "%d-%m-%Y %H:%M") - as.Date(df$c_jail_in, format = "%d-%m-%Y %H:%M") )

# Does the Compas score affect the number of days criminals will have to stay in prison?
# Yes, there is a slight positive correlation between the Compas score and the length of stay of criminals
cor(df$length_of_stay, df$decile_score)

# Extra
nrow(df)
ncol(df)
str(df)

summary(df)

# Task 2: Read and prepare the data for Risk of Recidivism
# Q5: Get the summary of race, gender, age, xtabs by sex and race
table(df$race)
table(df$sex)
table(df$age_cat)

round((table(df$race)/nrow(df))*100, 2)
round((table(df$sex)/nrow(df))*100, 2)
round((table(df$age_cat)/nrow(df))*100, 2)

xtabs(~ sex + race, data=df)

# Task 2: Read and prepare the data for Risk of Recidivism
# Q6: Plot the data with race and decile score
pblack <- ggplot(data=filter(df, race == "African-American"), aes(ordered(decile_score))) +
  geom_bar() +
  xlab("Decile Score") +
  ylim(0, 650) +
  ggtitle("Black Defendant's Decile Scores")
  
pwhite <- ggplot(data=filter(df, race == "Caucasian"), aes(ordered(decile_score))) +
  geom_bar() +
  xlab("Decile Score") +
  ylim(0, 650) +
  ggtitle("White Defendant's Decile Scores")
  
grid.arrange(pblack, pwhite, ncol = 2)

# Judges are often presented with two sets of scores from the Compas system - one that classifies people into High, Medium, and Low risk, and a corresponding decile score
# There is a clear downward trend in the decile score as those scores increase for the white defendants





# Task 3: Predict Racial Bias
# Q1: Change some variables (age, race, gender) into factors, and run a logistic regression, comparing low scores to high scores
df <- mutate(df, crime_factor = factor(c_charge_degree)) %>% 
  mutate(age_factor = as.factor(age_cat)) %>% 
  mutate(race_factor = factor(race)) %>% 
  within(race_factor <- relevel(race_factor, ref = 3)) %>% 
  mutate(gender_factor = factor(sex, levels = c("Male","Female"))) %>% 
  mutate(score_factor = factor(score_text != "Low", labels = c("LowScore","HighScore"))) 

# Check the structure  
str(df)

# Build logistic regression model
lrmodel <- glm(score_factor ~ gender_factor + age_factor + race_factor + priors_count + crime_factor + two_year_recid, family="binomial", data=df) 

# Check the summary and structure of model
summary(lrmodel) 
str(lrmodel)

### Optional 
control <- exp(-1.52554) / (1 + exp(-1.52554)) 
control 

# Black defendants are 45% more likely than white defendants to receive a higher score correcting for the seriousness of their crime, previous arrests, and future criminal behavior
exp(0.47721) / (1 - control + (control * exp(0.47721)))

<!-- ### Optional -->
<!-- # Evaulate the model -->
<!-- # Test goodness of fit -->
<!-- G2 <- pchisq(8483.3 - 6168.4, 6171 - 6160) -->
<!-- # A small value (close to 0) indicates that the full model is an improvement over the null model -->
<!-- # where null model is the one that has no explanatory variables (only includes a constant) -->
<!-- 1 - G2 -->





# Task 4: Read and prepare the data for Risk of Violent Recidivism
# Q1: Read the violent dataset to read the number of rows
# As mentioned in Q2 of Task 2, we are using one merged dataset that has both violent and non violent data, so this part is completed

# Task 4: Read and prepare the data for Risk of Violent Recidivism
# Q2: Remove rows based on following conditions
df2 <- dplyr::select(raw_data, age, c_charge_degree, race, age_cat, v_score_text, sex, priors_count, days_b_screening_arrest, v_decile_score, is_violent_recid, two_year_recid, c_jail_in, c_jail_out) %>%  
 filter(days_b_screening_arrest <= 30) %>%
 filter(days_b_screening_arrest >= -30) %>%
 filter(is_violent_recid != -1) %>%
 filter(c_charge_degree != "O") %>%
 filter(v_score_text != 'N/A')

# Task 4: Read and prepare the data for Risk of Violent Recidivism
# Q3: Get new column longer length of stay
df2$v_length_of_stay <- as.numeric( as.Date(df2$c_jail_out, format = "%d-%m-%Y %H:%M") - as.Date(df2$c_jail_in, format = "%d-%m-%Y %H:%M") )

# Does the Compas score affect the number of days criminals will have to stay in prison?
# Yes, there is a slight positive correlation between the Compas score and the length of stay of criminals
cor(df2$v_length_of_stay, df2$v_decile_score)

# Extra
nrow(df2)
ncol(df2)
str(df2)

summary(df2)

# Task 4: Read and prepare the data for Risk of Violent Recidivism
# Q4: Get the summary of race, age category
# Note: Also provided the summary of gender category and xtabs by sex and race
table(df2$race)
table(df2$age_cat)
table(df2$sex)

round((table(df2$race)/nrow(df2))*100,2)
round((table(df2$age_cat)/nrow(df2))*100,2)
round((table(df2$sex)/nrow(df2))*100,2)

xtabs(~ sex + race, data=df2)

# Task 4: Read and prepare the data for Risk of Violent Recidivism
# Q5: Plot the data with race and decile score
pblack2 <- ggplot(data=filter(df2, race =="African-American"), aes(ordered(v_decile_score))) +
  geom_bar() +
  xlab("Violent Decile Score") +
  ylim(0, 850) +
  ggtitle("Black Defendant's Violent Decile Scores")

pwhite2 <- ggplot(data=filter(df2, race =="Caucasian"), aes(ordered(v_decile_score))) +
  geom_bar() +
  xlab("Violent Decile Score") +
  ylim(0, 850) +
  ggtitle("White Defendant's Violent Decile Scores")

grid.arrange(pblack2, pwhite2,  ncol = 2)

# In this case, there is a downward trend for both black and white defendants decile scores as those scores increase
# However, the decrease for black defendants' deciles scores is more gradual whereas the decrease is steep for that of white defendants
# Looking at the total numbers, black defendants are still much more likely to get a higher decile score than white defendants for violent recidivism


### Optional
df2 <- mutate(df2, crime_factor = factor(c_charge_degree)) %>% 
 mutate(age_factor = as.factor(age_cat)) %>% 
 mutate(race_factor = factor(race)) %>% 
 within(race_factor <- relevel(race_factor, ref = 3)) %>% 
 mutate(gender_factor = factor(sex, levels= c("Male","Female"))) %>% 
 mutate(score_factor = factor(v_score_text != "Low", labels = c("LowScore","HighScore"))) 

str(df2)

lrmodel_2 <- glm(score_factor ~ gender_factor + age_factor + race_factor + priors_count + crime_factor + two_year_recid, family="binomial", data=df2) 

summary(lrmodel_2)

control <- exp(-2.167673) / (1 + exp(-2.167673)) 
control

# Black defendants are 72% more likely than white defendants to receive a higher score correcting for the seriousness of their crime, previous arrests, and future criminal behavior 
exp(0.627982) / (1 - control + (control * exp(0.627982)))

<!-- ### Optional -->
<!-- # Evaulate the model -->
<!-- # Test goodness of fit -->
<!-- G2 <- pchisq(7853.9 - 5160.4, 6171 - 6160) -->
<!-- # A small value (close to 0) indicates that the full model is an improvement over the null model -->
<!-- # where null model is the one that has no explanatory variables (only includes a constant) -->
<!-- 1 - G2 -->





# Task 5: Predict Accuracy (Non Violent Recidivism with respect to Race)
# Q1: Read the cox-parsed.csv dataset to read the number of rows
library(survival) 
library(ggfortify) 

df3 = read.csv("C:/Users/benny/Desktop/My-Docs/Jobs-2022/Course-NotJob/Module4-Downloads/Project/cox-parsed.csv") 

nrow(df3)

# Task 5: Predict Accuracy (Non Violent Recidivism with respect to Race)
# Q2: Get summary of score factor and race factor
data <- filter(filter(df3 , score_text != "N/A"), end > start) %>% 
 mutate(race_factor = factor(race)) %>%
 within(race_factor <- relevel(race_factor, ref = 3)) %>%
 mutate(score_factor = factor(score_text)) %>%
 within(score_factor <- relevel(score_factor, ref=2))
 
nrow(data)

# Remove duplicated rows
grp <- data[!duplicated(data$id),] 

nrow(grp) 

str(grp)

summary(grp$score_factor)
summary(grp$race_factor)

# Task 5: Predict Accuracy (Non Violent Recidivism with respect to Race)
# Q3: Test algorithm for Logistic regression on Black and white defendants
# Logistic Regression for non violent recidivism was already performed in Task 3

# Task 5: Predict Accuracy (Non Violent Recidivism with respect to Race)
# Q4: Get summary of fit, white fit and black fit
# Using the survival function
f <- Surv(start, end, event, type="counting") ~ score_factor 

summary(f)

plotty <- function(fit, title) { 
 return(autoplot(fit, conf.int=T, censor=F) + ggtitle(title) + ylim(0,1))
}

overall_fit <- survfit(f, data=grp)
summary(overall_fit, times=c(730))

white <- filter(grp, race == "Caucasian") 
white_fit <- survfit(f, data=white)
summary(white_fit, times=c(730))

black <- filter(grp, race == "African-American") 
black_fit <- survfit(f, data=black)
summary(black_fit, times=c(730))

# Task 5: Predict Accuracy (Non Violent Recidivism with respect to Race)
# Q5: Get summary of coxph for white and black data

### Optional - overall
plotty(overall_fit, "Overall - Non Violent")

grid.arrange(plotty(white_fit, "White defendants (Non Violent)"), plotty(black_fit, "Black defendants (Non Violent)"), ncol=2)





# Task 6: Predict Accuracy (Violent Recidivism with respect to Race)
# Q1: Read cox-violent parsed.csv
df4 = read.csv("C:/Users/benny/Desktop/My-Docs/Jobs-2022/Course-NotJob/Module4-Downloads/Project/cox-violent-parsed.csv") 

nrow(df4)

# Task 6: Predict Accuracy (Violent Recidivism with respect to Race)
# Q2: Print white and black defendants
violent_data <- filter(filter(df4, score_text != "N/A"), end > start) %>% 
 mutate(race_factor = factor(race)) %>% 
 within(race_factor <- relevel(race_factor, ref = 3)) %>% 
 mutate(score_factor = factor(score_text)) %>% 
 within(score_factor <- relevel(score_factor, ref=2))

# Remove duplicated rows
vgrp <- violent_data[!duplicated(violent_data$id),] 

nrow(vgrp)

# Using the survival function
vf <- Surv(start, end, event, type="counting") ~ score_factor 

vmodel <- coxph(vf, data=vgrp) 

summary(vmodel)

# White and Black Fit
vwhite <- filter(vgrp, race == "Caucasian") 
vwhite_fit <- survfit(vf, data=vwhite) 

vblack <- filter(vgrp ,race == "African-American") 
vblack_fit <- survfit(vf, data=vblack) 

### Optional - overall
voverall_fit <- survfit(vf, data=vgrp) 

plotty(voverall_fit, "Overall - Violent")  

grid.arrange(plotty(vwhite_fit, "White defendants (Violent)"), plotty(vblack_fit, "Black defendants (Violent)"), ncol=2)





# Task 7: Predict Accuracy (Non Violent and Violent Recidivism with respect to Gender)
# Q1: Read cox-parsed.csv and cox-violent	parsed.csv
# Datasets are already read in Tasks 5 and 6

# Task 7: Predict Accuracy (Non Violent and Violent Recidivism with respect to Gender)
# Q2: Print male and female defendants

# Non Violent Recidivism 
female <- filter(grp, sex == "Female")
male   <- filter(grp, sex == "Male")

f2 <- Surv(start, end, event, type="counting") ~ score_factor 

male_fit <- survfit(f2, data=male) 
female_fit <- survfit(f2, data=female)

summary(male_fit, times=c(730)) 
summary(female_fit, times=c(730)) 

grid.arrange(plotty(female_fit, "Female defendants (Non Violent)"), plotty(male_fit, "Male defendants (Non Violent)"), ncol=2)

# violent Recidivism 
vfemale <- filter(vgrp, sex == "Female")
vmale   <- filter(vgrp, sex == "Male") 

vf2 <- Surv(start, end, event, type="counting") ~ score_factor 

v_male_fit <- survfit(vf2, data=vmale)
v_female_fit <- survfit(vf2, data=vfemale) 

summary(v_male_fit, times=c(730))
summary(v_female_fit, times=c(730)) 

grid.arrange(plotty(v_female_fit, "Female defendants (Violent)"), plotty(v_male_fit, "Male defendants (Violent)"), ncol=2)

